const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');const root=path.resolve(__dirname,'..');const read=f=>fs.readFileSync(path.join(root,f),'utf8');
(async()=>{const data={'t3next_user':JSON.stringify({id:'cash',tenant_id:'A'}),'datapos_cache:/users':JSON.stringify([{pin:'sensitive-old'}]),'datapos_cache:/users/admin':JSON.stringify({pin:'sensitive-old'}),'datapos_cache:/products':'keep'};
const st={get length(){return Object.keys(data).length},key:i=>Object.keys(data)[i],getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v,removeItem:k=>delete data[k]};let failure;
const ctx={Date,Math,JSON,Error,Number,String,Object,console,localStorage:st,navigator:{onLine:true},window:{dispatchEvent(){},addEventListener(){},removeEventListener(){}},CustomEvent:class{},Event:class{},setTimeout,clearTimeout,setInterval,clearInterval};vm.createContext(ctx);vm.runInContext(read('frontend/src/lib/offline.js').replace(/export default offlineApi;/,'').replace(/export (const|let) /g,'var ').replace(/export function /g,'function '),ctx);
assert.equal(ctx.isQueueable('/products/register-with-admin'),false);assert.equal(ctx.isQueueable('/products/register-with-admin?x=1'),false);assert.equal(ctx.isQueueable('/products'),true);assert.equal(ctx.isCacheable('/users'),false);ctx.attachInterceptors({interceptors:{response:{use:(ok,bad)=>failure=bad}}});assert(!data['datapos_cache:/users']);assert(!data['datapos_cache:/users/admin']);assert.equal(data['datapos_cache:/products'],'keep');console.log('PASS actual offline policy blocks approval queueing and removes legacy PIN caches');
await assert.rejects(()=>failure({message:'Network Error',config:{method:'post',url:'/products/register-with-admin',data:{admin_pin:'1357'}}}));assert.equal(ctx.getQueue().length,0);assert(!JSON.stringify(data).includes('1357'));console.log('PASS approval network failure rejects without persisting the PIN or product');
const hook=read('frontend/src/lib/usePOSSearchFocus.js'),pos=read('frontend/src/pages/POS.jsx'),component=read('frontend/src/components/POSProductRegistration.jsx');assert(hook.includes('isEditableTarget(active) && active !== ref.current'));assert(hook.includes('hasOpenDialog()'));assert(hook.includes("window.removeEventListener('keydown', key, true)"));assert(pos.includes('loadData(true)'));assert(pos.includes('usePOSSearchFocus(searchRef, scanReady'));assert(pos.includes("error.response?.data?.detail === 'Produkti nuk u gjet'"));console.log('PASS scanner lifecycle preserves edited inputs/dialogs and uses background post-sale refresh');
assert(component.includes('if (locked.current) return'));assert(component.includes('const adminPin = pin; setPin'));assert(component.includes('usePaymentViewport(true)'));assert(!component.includes('localStorage'));assert(component.includes("if (stage === 'product') { setStage('approval'); return; }"));console.log('PASS product details precede PIN approval, single-flight and secret clearing remain in actual component');
})().catch(e=>{console.error(e);process.exitCode=1});
