const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,'frontend/src/lib',f),'utf8');
function storage(){const data={};return {data,fail:false,getItem:k=>data[k]??null,setItem(k,v){if(this.fail)throw new Error('quota');data[k]=v;},removeItem:k=>delete data[k]};}
function load(source,extra={}){const ctx={Date,Math,JSON,Error,BigInt,Number,String,Object,console,...extra};vm.createContext(ctx);vm.runInContext(source.replace(/export default offlineApi;/,'').replace(/export (const|let) /g,'var ').replace(/export function /g,'function '),ctx);return ctx;}
async function run(){
const money=load(read('saleMoney.js'));assert.deepEqual(JSON.parse(JSON.stringify(money.calculateSaleLine({quantity:3,unit_price:.335,discount_percent:10,vat_percent:18}))),{subtotal:1.01,discount:.1,vat:.16,total:1.07});assert.equal(money.toCents('1.005'),101);assert.equal(money.sumSaleLines([{quantity:1,unit_price:.1},{quantity:1,unit_price:.2}]).total,.3);assert.equal(money.toCents('1e-2'),1);console.log('PASS exact cents/half-up line math matches server, including scientific decimal input');
const st=storage(),user={id:'u1',tenant_id:'t1'},a=load(read('saleAttempt.js'),{localStorage:st});const payload={items:[{product_id:'p1',quantity:1}],cash_amount:1};let first=a.prepareSaleAttempt(payload,user);assert.equal(a.prepareSaleAttempt(payload,user).key,first.key);assert.throws(()=>a.prepareSaleAttempt({...payload,cash_amount:2},user));assert.equal(a.pendingSaleAttempt(user).key,first.key);a.releaseRejectedSaleAttempt({response:{status:503}},user);assert.equal(a.pendingSaleAttempt(user).key,first.key);a.releaseRejectedSaleAttempt({response:{status:400}},user);assert.equal(a.pendingSaleAttempt(user),null);st.fail=true;assert.throws(()=>a.prepareSaleAttempt(payload,user));st.fail=false;console.log('PASS request ID persists across retry/refresh; uncertain requests cannot become new sales; quota stops send');
const s=storage();s.setItem('t3next_user',JSON.stringify(user));const events=[];const ctx=load(read('offline.js'),{localStorage:s,navigator:{onLine:true},window:{dispatchEvent:e=>events.push(e),addEventListener(){},removeEventListener(){}},CustomEvent:class{constructor(name,detail){this.name=name;this.detail=detail;}},Event:class{constructor(name){this.name=name;}},setTimeout,clearTimeout,setInterval,clearInterval});
let entry=ctx.enqueue({method:'post',url:'/sales',data:{...payload,request_id:'request-test-1'}});assert.equal(ctx.enqueue({method:'post',url:'/sales',data:{...payload,request_id:'request-test-1'}}).id,entry.id);assert.equal(ctx.getQueue().length,1);let config;await ctx.flushQueue({request:async c=>{config=c;return {data:{id:'saved'}};}});assert.equal(config.headers['Idempotency-Key'],'request-test-1');assert.equal(ctx.getQueue().length,0);console.log('PASS offline deduplicates locally and preserves the server idempotency key');
ctx.enqueue({method:'post',url:'/sales',data:{request_id:'request-reject'}});await ctx.flushQueue({request:async()=>{throw {response:{status:422,data:{detail:'Invalid'}}};}});assert.equal(ctx.getQueue().length,1);assert.equal(ctx.getQueue()[0].status,'blocked');await ctx.retryBlocked({request:async()=>({data:{id:'saved'}})});assert.equal(ctx.getQueue().length,0);console.log('PASS rejected sales retain payload/error and retry does not assign a new identity');
ctx.enqueue({method:'post',url:'/sales',data:{request_id:'request-auth-1'}});await ctx.flushQueue({request:async()=>{throw {response:{status:401}};}});assert.equal(ctx.getQueue()[0].status,'pending');let calls=0;s.setItem('t3next_user',JSON.stringify({id:'u2',tenant_id:'t2'}));await ctx.flushQueue({request:async()=>{calls++;}});assert.equal(calls,0);assert.equal(ctx.getQueue().length,1);s.setItem('t3next_user',JSON.stringify(user));await ctx.flushQueue({request:async()=>({data:{}})});console.log('PASS session errors retain queue and another tenant/user cannot replay it');
ctx.enqueue({method:'post',url:'/sales',data:{request_id:'request-first'}});await ctx.flushQueue({request:async()=>{ctx.enqueue({method:'post',url:'/sales',data:{request_id:'request-arrived'}});return {data:{}};}});assert.equal(ctx.getQueue().length,1);assert.equal(ctx.getQueue()[0].data.request_id,'request-arrived');console.log('PASS arrivals during sync are retained rather than overwritten');
ctx.writeCache('/products',[{id:'private'}]);assert(ctx.readCache('/products'));s.setItem('t3next_user',JSON.stringify({id:'u2',tenant_id:'t2'}));assert.equal(ctx.readCache('/products'),null);s.setItem('t3next_user',JSON.stringify(user));s.fail=true;assert.throws(()=>ctx.enqueue({method:'post',url:'/sales',data:{request_id:'request-quota'}}));s.fail=false;console.log('PASS cache belongs to one account; queue storage failure is never reported as success');
const pos=fs.readFileSync(path.join(root,'frontend/src/pages/POS.jsx'),'utf8');assert(pos.includes("'Idempotency-Key': attempt.key"));assert(pos.includes('releaseRejectedSaleAttempt(error, user)'));assert(pos.includes('if (printReceipt && !queued)'));assert(pos.indexOf('setCart([]);',pos.indexOf('const handlePayment'))<pos.indexOf('printThermalReceipt({...response.data',pos.indexOf('const handlePayment')));console.log('PASS POS separates queued/confirmed sales and printing failure cannot re-submit a completed sale');
}
run().catch(e=>{console.error(e);process.exitCode=1});
